version: "3"
services:
  server:
    container_name: express
    build:
      context: .
      dockerfile: Dockerfile
    image: node:16.13.0
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 3000:3000
    working_dir: /app
    command: npm start
    networks:
      - my_net
    restart: always

networks:
  my_net:
    driver: bridge